---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:11.0.0
  amd64: ghcr.io/home-assistant/amd64-base:11.0.0
  armhf: ghcr.io/home-assistant/armhf-base:11.0.0
  armv7: ghcr.io/home-assistant/armv7-base:11.0.0
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
