---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  arm64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
codenotary:
  base_image: notary@home-assistant.io
  signer: notary@home-assistant.io
