---
name: etcd Server
version: "0.1.4"
slug: etcd
description: A distributed, reliable key-value store for the most critical data of a distributed system
url: https://github.com/alsotoes/hassio-infrastructure/tree/main/etcd
init: false
arch:
  - armv7
  - aarch64
  - amd64
panel_admin: false
ports:
  2379/tcp: 2379
  2380/tcp: 2380
startup: system
timeout: 300
apparmor: false
map:
  - type: data
    read_only: false
