---
name: SMB1 Proxy
slug: smb1_proxy
description: "Bridge legacy SMB1 devices (Apple Time Capsule) to modern SMB2/3 with web monitoring and auto-recovery."
version: "1.3.2"
url: "https://github.com/alsotoes/hassio-infrastructure/tree/main/smb1-proxy"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
init: false
host_network: true
healthcheck: "/usr/local/bin/health-check"
ingress: true
ingress_port: 9876
ports:
  9876/tcp: 9876

apparmor: false
privileged:
  - SYS_ADMIN
devices:
  - /dev/fuse:/dev/fuse:rwm

map:
  - share:rw
  - addon_config:rw

schema:
  tc_host: str
  tc_share: str
  tc_username: str
  tc_password: str
  tc_domain: str?
  mount_point: str
  reexport_share_name: str
  allow_ntlmv1: bool
  allow_smb1: bool
  hosts_allow:
    - str
  interfaces?:
    - str
  expose_in_share: bool
  share_link_name: str
  advertise_mdns: bool
  mdns_hostname: str
  netbios_name: str

options:
  tc_host: "timecapsule.local"
  tc_share: "Data"
  tc_username: "admin"
  tc_password: "password"
  tc_domain: ""
  mount_point: "/data/timecapsule"
  reexport_share_name: "timecapsule"
  allow_ntlmv1: true
  allow_smb1: true
  hosts_allow:
    - "192.168.0.0/16"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
  interfaces: []
  expose_in_share: true
  share_link_name: "timecapsule"
  advertise_mdns: false
  mdns_hostname: "smb1-gw"
  netbios_name: "SMB1GW"
