---
name: AFP to S3
version: "0.1.7"
slug: afp2s3
description: Mounts an AFP share and exposes it as an S3 endpoint using Minio.
url: https://github.com/alsotoes/hassio-infrastructure/tree/main/afp2s3
apparmor: false
ingress: true
ingress_port: 9001
arch:
  - amd64
  - armv7
  - aarch64
init: false
map:
  - ssl
options:
  afp_server: "afp://server/share"
  afp_user: "user"
  afp_password: "password"
schema:
  afp_server: str
  afp_user: str
  afp_password: password
webui: "http://[HOST]:[PORT:9001]/"
ports:
  9000/tcp: 9000
  9001/tcp: 9001
