---
name: AFP to S3
version: "0.1.11"
slug: afp2s3
description: Mounts an AFP share and exposes it as an S3 endpoint using Minio.
url: https://github.com/alsotoes/hassio-infrastructure-dev/tree/main/afp2s3
apparmor: false
ingress: true
ingress_port: 9001
arch:
  - amd64
  - armv7
  - aarch64
init: true
map:
  - ssl
devices:
  - /dev/fuse
privileged:
  - SYS_ADMIN
options:
  afp_server: "afp://server/share"
  afp_user: "user"
  afp_password: "password"
  afp_share: ""
  afp_marker: ".com.apple.timemachine.supported"
schema:
  afp_server: str
  afp_user: str
  afp_password: password
  afp_share: str?
  afp_marker: str?
webui: "http://[HOST]:[PORT:9001]/"
ports:
  9000/tcp: 9000
  9001/tcp: 9001
