#!/command/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

bashio::log.info "TerraGUI: Starting..."

# Set environment variable for app root
export TGM_ROOT_DIR="/app"

# Start the application
exec python3 /app/run.py --port 5005