---
name: Atlas
version: "0.0.10"
logo: logo.png
icon: icon.png
slug: atlas
description: Network Infrastructure Visualizer
arch:
  - amd64
  - aarch64
  - armv7
init: false
panel_icon: mdi:lan
panel_title: Atlas
webui: "http://[HOST]:[PORT:8888]"
ingress: true
ingress_port: 8888
ingress_stream: true
startup: services
ports:
  8888/tcp: 8888
  8889/tcp: 8889
ports_description:
  8888/tcp: Web UI
  8889/tcp: API
host_network: true
host_pid: true
docker_api: true
apparmor: false
hassio_api: true
homeassistant_api: false
udev: true
map:
  - addon_config: rw
  - share: rw
